apiVersion: apps/v1
kind: Deployment
metadata:
  name: zulip-nginx
  namespace: zulip
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zulip
      component: nginx
  template:
    metadata:
      labels:
        app: zulip
        component: nginx
    spec:
      containers:
        - image: 10.110.0.3:5000/zulip/nginx:1.20
          name: nginx
          ports:
          - containerPort: 80 
            name: nginx 
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: nginx-conf
          configMap:
            name: zulip-nginx-conf
            items:
               - key: nginx.conf
                 path: nginx.conf

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: zulip-nginx-conf
  namespace: zulip
data:
  nginx.conf: |
    user nginx;

    worker_processes 2;
    pid /var/run/nginx.pid;

    worker_rlimit_nofile 40000;
    events {
        worker_connections 40000;
        use epoll;
        multi_accept on;
    }

    http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        client_max_body_size 24m;

        default_type application/octet-stream;
        include /etc/nginx/mime.types;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        reset_timedout_connection on;

        gzip on;
        gzip_disable "msie6";
        gzip_proxied any;
        gzip_types
          application/javascript
          application/json
          application/xml
          application/x-javascript
          image/svg+xml
          text/css
          text/javascript
          text/plain;
        gzip_vary on;

        # https://wiki.mozilla.org/Security/Server_Side_TLS intermediate profile
        #ssl_session_timeout 1d;
        #ssl_session_cache shared:SSL:50m;
        #ssl_session_tickets off;
        #ssl_dhparam /etc/nginx/dhparam.pem;
        #ssl_protocols TLSv1.2 TLSv1.3;
        #ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        #ssl_prefer_server_ciphers off;
        #ssl_stapling on;
        #ssl_stapling_verify on;
        #ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;

        server {
          listen 80;
          listen [::]:80;
          server_name             zulip.k3s;

          location / {
              gzip_static on;
              proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header        Host $http_host;
              proxy_http_version      1.1;
              proxy_buffering         off;
              proxy_read_timeout      20m;
              proxy_pass              http://zulip:80/;
          }
        }
    }
    