apiVersion: v1
kind: ConfigMap
metadata:
  name: zulip-rabbitmq-config
  namespace: zulip
data:
  enabled_plugins: |
    [rabbitmq_peer_discovery_k8s, rabbitmq_management, rabbitmq_prometheus].
  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend = k8s
    cluster_formation.k8s.host = kubernetes.default.svc.cluster.local
    cluster_formation.k8s.address_type = hostname
    cluster_formation.k8s.service_name = zulip-rabbitmq
    queue_master_locator=min-masters