apiVersion: v1
kind: Service
metadata:
  name: zulip-rabbitmq
  namespace: zulip
  labels:
    app: zulip
spec:
  selector:
    app: zulip
    component: rabbitmq
  clusterIP: None
  ports:
  - name: epmd
    port: 4369
    protocol: TCP
    targetPort: 4369
  - name: cluster-rpc
    port: 25672
    protocol: TCP
    targetPort: 25672
  type: ClusterIP
  sessionAffinity: None