apiVersion: v1
kind: Service
metadata:
  name: zulip-redis
  namespace: zulip
  labels:
    app: zulip
spec:
  type: ClusterIP
  selector:
    app: zulip
    component: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  - name: gossip
    port: 16379
    targetPort: 16379
    protocol: TCP