apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zulip-data
  namespace: zulip
  labels:
    app: zulip
    tier: data
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi